%This file was automatically generated by--Generate_RobotPlot--
clear L
clear Daux
clear Dr
clear sigma
sigma(1,1)=0;
sigma(2,1)=0;
sigma(3,1)=0;
Daux(1,1)=1.570796e+00;%alfa
Daux(1,2)=0;%a
Daux(1,4)=5.000000e-01;%D
Daux(1,3)=0;%theta
Daux(2,1)=0;%alfa
Daux(2,2)=4.000000e-01;%a
Daux(2,4)=0;%D
Daux(2,3)=0;%theta
Daux(3,1)=0;%alfa
Daux(3,2)=4.000000e-01;%a
Daux(3,4)=0;%D
Daux(3,3)=0;%theta
fprintf(1,'     alfa      a        theta      d      sigma\n');
Dr=[Daux,sigma]
L{1}=(link(Dr(1,:),'standard'));
L{2}=(link(Dr(2,:),'standard'));
L{3}=(link(Dr(3,:),'standard'));
base=[0 1 0 0;-1 0 0 0;0 0 1 0;0 0 0 1];
clear Robot_robotF
Robot_robotF=robot(L,'Robot-robotP','Fabricante_robot');
Robot_robotF.base=base;
Robot_robotF.plotopt={'nobase'};
% Robot_robotF.plotopt={'nobase' 'workspace' [-1.5 1.5 -1.5 1.5 -0.1 1.5] 'mag' 13};
clear L
clear Dr
clear Daux
clear sigma
